import React from 'react';
import { ShieldCheck } from 'lucide-react';

interface LeadershipDisclaimerProps {
  customText?: string;
  compact?: boolean;
}

export const LeadershipDisclaimer: React.FC<LeadershipDisclaimerProps> = ({ customText, compact = false }) => {
  return (
    <div
      className={`flex items-start gap-2.5 bg-[#E8F4FB] border border-[#D7E4EE] rounded-xl text-[#19324A] ${
        compact ? 'p-2.5 text-[11px]' : 'p-3.5 text-xs'
      }`}
    >
      <ShieldCheck className="w-4 h-4 text-[#2F6EA6] shrink-0 mt-0.5" />
      <div className="leading-relaxed">
        <span className="font-bold text-[#163A63]">Leadership Decision Support: </span>
        <span>
          {customText ||
            'Strategic plans generated by Agent 72 are decision-support artifacts. Final approval, resource allocation and institutional strategy remain with institutional leadership/governing bodies.'}
        </span>
      </div>
    </div>
  );
};

