"""Domain models for Phase 8 — Strategic Plan Generation & Execution Framework."""

from dataclasses import dataclass, field
from datetime import date, datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
import uuid


class OptionDecisionStatus(str, Enum):
    """Lifecycle status of a strategic option in relation to strategic planning."""
    CANDIDATE = "CANDIDATE"
    SELECTED_FOR_PLANNING = "SELECTED_FOR_PLANNING"
    IN_PLAN = "IN_PLAN"
    DEFERRED = "DEFERRED"
    REJECTED = "REJECTED"


class PlanStatus(str, Enum):
    """Lifecycle status of a strategic plan."""
    DRAFT = "DRAFT"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    ACTIVE = "ACTIVE"
    UNDER_REVIEW = "UNDER_REVIEW"
    COMPLETED = "COMPLETED"
    ARCHIVED = "ARCHIVED"


class ObjectiveStatus(str, Enum):
    """Execution status of a strategic objective."""
    PROPOSED = "PROPOSED"
    APPROVED = "APPROVED"
    ACTIVE = "ACTIVE"
    AT_RISK = "AT_RISK"
    COMPLETED = "COMPLETED"
    DEFERRED = "DEFERRED"
    CLOSED = "CLOSED"


class InitiativeStatus(str, Enum):
    """Execution status of an initiative."""
    PLANNED = "PLANNED"
    APPROVED = "APPROVED"
    ACTIVE = "ACTIVE"
    AT_RISK = "AT_RISK"
    COMPLETED = "COMPLETED"
    DEFERRED = "DEFERRED"
    CANCELLED = "CANCELLED"


class MilestoneStatus(str, Enum):
    """Status of an initiative milestone."""
    NOT_STARTED = "NOT_STARTED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    DELAYED = "DELAYED"
    MISSED = "MISSED"


class ReviewStatus(str, Enum):
    """Deterministic review status for target, objective, or plan."""
    ON_TRACK = "ON_TRACK"
    AT_RISK = "AT_RISK"
    OFF_TRACK = "OFF_TRACK"
    COMPLETED = "COMPLETED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class TargetDirection(str, Enum):
    """Directionality of metric targets."""
    HIGHER_IS_BETTER = "HIGHER_IS_BETTER"
    LOWER_IS_BETTER = "LOWER_IS_BETTER"
    TARGET_RANGE = "TARGET_RANGE"
    NEUTRAL = "NEUTRAL"


class TargetStatus(str, Enum):
    """Target lifecycle and verification status."""
    OBSERVED_BASELINE = "OBSERVED_BASELINE"
    PROPOSED_TARGET = "PROPOSED_TARGET"
    APPROVED_TARGET = "APPROVED_TARGET"
    REQUIRING_METRIC_DEFINITION = "REQUIRING_METRIC_DEFINITION"


class ResourceRequirement(str, Enum):
    """Resource requirement level. Exact budgets must never be fabricated."""
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    UNKNOWN = "UNKNOWN"


class DiagnosticSignalType(str, Enum):
    """Types of diagnostic review signals."""
    MILESTONE_DELAYED = "MILESTONE_DELAYED"
    TARGET_OFF_TRACK = "TARGET_OFF_TRACK"
    TARGET_AT_RISK = "TARGET_AT_RISK"
    EVIDENCE_STALE = "EVIDENCE_STALE"
    DEPENDENCY_BLOCKED = "DEPENDENCY_BLOCKED"
    RESOURCE_CONSTRAINT = "RESOURCE_CONSTRAINT"
    OBJECTIVE_IMPROVING = "OBJECTIVE_IMPROVING"
    OBJECTIVE_DECLINING = "OBJECTIVE_DECLINING"


LEADERSHIP_DECISION_SUPPORT_DISCLAIMER = (
    "Strategic plans generated by Agent 72 are decision-support artifacts. "
    "Final approval, resource allocation and institutional strategy remain "
    "with institutional leadership/governing bodies."
)


@dataclass
class StrategicTarget:
    """Measurable target linked to an objective and canonical MetricDefinition."""
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    objective_id: str = ""
    metric_key: str = ""
    metric_definition_id: Optional[str] = None
    baseline_value: Optional[float] = None
    baseline_period: Optional[str] = None
    target_value: Optional[float] = None
    target_period: Optional[str] = None
    direction: TargetDirection = TargetDirection.HIGHER_IS_BETTER
    unit: str = "count"
    measurement_frequency: str = "ANNUAL"
    evidence_ids: List[str] = field(default_factory=list)
    confidence: float = 1.0
    assumptions: List[str] = field(default_factory=list)
    status: TargetStatus = TargetStatus.PROPOSED_TARGET
    gap: Optional[float] = None
    gap_unit_label: str = ""
    target_provenance: str = "DERIVED_FROM_EVIDENCE"


@dataclass
class InitiativeMilestone:
    """Concrete milestone within a strategic initiative."""
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    initiative_id: str = ""
    title: str = ""
    description: Optional[str] = None
    due_period: str = ""
    status: MilestoneStatus = MilestoneStatus.NOT_STARTED
    completion_percentage: float = 0.0
    evidence_ids: List[str] = field(default_factory=list)
    target_date: Optional[date] = None
    completion_date: Optional[date] = None


@dataclass
class PlanInitiative:
    """Actionable program or project delivering on a strategic objective."""
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    objective_id: str = ""
    title: str = ""
    description: Optional[str] = None
    rationale: Optional[str] = None
    owner_unit_id: str = "TO_BE_ASSIGNED"
    supporting_units: List[str] = field(default_factory=list)
    source_option_ids: List[str] = field(default_factory=list)
    dependencies: List[str] = field(default_factory=list)
    resource_requirement: ResourceRequirement = ResourceRequirement.UNKNOWN
    implementation_risk: str = "MEDIUM"
    start_period: str = ""
    end_period: str = ""
    status: InitiativeStatus = InitiativeStatus.PLANNED
    success_criteria: List[str] = field(default_factory=list)
    evidence_ids: List[str] = field(default_factory=list)
    milestones: List[InitiativeMilestone] = field(default_factory=list)


@dataclass
class StrategicObjective:
    """High-level institutional strategic outcome."""
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    strategic_plan_id: str = ""
    title: str = ""
    description: Optional[str] = None
    strategic_rationale: Optional[str] = None
    source_option_ids: List[str] = field(default_factory=list)
    strategic_issue_ids: List[str] = field(default_factory=list)
    related_metrics: List[str] = field(default_factory=list)
    status: ObjectiveStatus = ObjectiveStatus.PROPOSED
    priority: str = "MEDIUM"
    owner_unit_id: str = "TO_BE_ASSIGNED"
    assumptions: List[str] = field(default_factory=list)
    confidence: float = 1.0
    targets: List[StrategicTarget] = field(default_factory=list)
    initiatives: List[PlanInitiative] = field(default_factory=list)


@dataclass
class TargetVariance:
    """Direction-aware variance calculation for a measurable target."""
    metric_key: str
    metric_definition_id: Optional[str] = None
    baseline_value: Optional[float] = None
    target_value: Optional[float] = None
    observed_value: Optional[float] = None
    observed_period: Optional[str] = None
    absolute_variance: Optional[float] = None
    relative_variance: Optional[float] = None
    unit: str = "count"
    is_percentage: bool = False
    variance_notation: str = ""
    direction: TargetDirection = TargetDirection.HIGHER_IS_BETTER
    status: ReviewStatus = ReviewStatus.INSUFFICIENT_EVIDENCE
    notes: Optional[str] = None


@dataclass
class CorrectiveActionCandidate:
    """Candidate corrective action produced by review, requiring leadership decision."""
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    objective_id: Optional[str] = None
    initiative_id: Optional[str] = None
    signal_type: DiagnosticSignalType = DiagnosticSignalType.TARGET_OFF_TRACK
    title: str = ""
    description: str = ""
    suggested_action: str = ""
    rationale: str = ""
    requires_leadership_approval: bool = True


@dataclass
class ExecutionReview:
    """Immutable periodic or annual execution review snapshot."""
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    strategic_plan_id: str = ""
    review_period: str = ""
    review_date: date = field(default_factory=lambda: datetime.now(timezone.utc).date())
    overall_status: ReviewStatus = ReviewStatus.ON_TRACK
    progress_summary: str = ""
    objective_statuses: Dict[str, str] = field(default_factory=dict)
    initiative_statuses: Dict[str, str] = field(default_factory=dict)
    milestone_statuses: Dict[str, str] = field(default_factory=dict)
    metric_variances: List[TargetVariance] = field(default_factory=list)
    diagnostic_signals: List[Dict[str, Any]] = field(default_factory=list)
    risks: List[Dict[str, Any]] = field(default_factory=list)
    corrective_actions: List[CorrectiveActionCandidate] = field(default_factory=list)
    assumptions: List[str] = field(default_factory=list)
    evidence_ids: List[str] = field(default_factory=list)
    confidence: float = 1.0
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass
class StrategicPlan:
    """Comprehensive institutional strategic plan."""
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    institution_id: Optional[str] = None
    institution_name: str = ""
    title: str = ""
    horizon_start_year: int = 2026
    horizon_end_year: int = 2030
    source_analysis_ids: List[str] = field(default_factory=list)
    selected_option_ids: List[str] = field(default_factory=list)
    objectives: List[StrategicObjective] = field(default_factory=list)
    ownership_summary: Dict[str, List[str]] = field(default_factory=dict)
    assumptions: List[str] = field(default_factory=list)
    vision_statement: Optional[str] = None
    mission_statement: Optional[str] = None
    existing_commitments: Optional[str] = None
    review_period: str = "ANNUAL"
    decision_support_disclaimer: str = LEADERSHIP_DECISION_SUPPORT_DISCLAIMER
    status: PlanStatus = PlanStatus.DRAFT
    engine_version: str = "1.0.0"
    previous_version_id: Optional[str] = None
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    execution_reviews: List[ExecutionReview] = field(default_factory=list)
    strategic_options: List[Dict[str, Any]] = field(default_factory=list)
    scenarios: List[Dict[str, Any]] = field(default_factory=list)

