import React, { useState } from 'react';
import { Send, Sparkles, Database, ArrowRight, ShieldCheck, Bot } from 'lucide-react';
import { api } from '../../api/client';
import { AgentQueryResponse } from '../../api/types';
import { StructuredMessageView } from './StructuredMessageView';

interface Message {
  id: string;
  sender: 'user' | 'agent';
  text: string;
  confidence?: number;
  groundingSources?: any[];
  relatedMetrics?: string[];
  suggestedQuestions?: string[];
  disclaimer?: string;
}

interface AskAgent72ViewProps {
  institutionId: string;
  period: string;
}

export const AskAgent72View: React.FC<AskAgent72ViewProps> = ({ institutionId, period }) => {
  const [messages, setMessages] = useState<Message[]>([
    {
      id: 'welcome-1',
      sender: 'agent',
      text: "Hello! I'm Agent 72. Ask me about your institution's current position, longitudinal trajectory, strategic risks, evaluated options, or execution plan progress.",
      disclaimer:
        'Strategic plans and analyses generated by Agent 72 are decision-support artifacts. Final approval, resource allocation and institutional strategy remain with institutional leadership/governing bodies.',
    },
  ]);
  const [inputText, setInputText] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  const quickPrompts = [
    'What should the Computer Science and Engineering department focus on over the next academic year, given our placement trends, research output, and faculty profile?',
    'Where are we currently underperforming against targets?',
    'What strategic risks should leadership focus on?',
    'Which strategic options are highest priority?',
    'How is our strategic plan progressing?',
    'What targets are currently at risk?',
  ];

  const handleSend = async (textToSend?: string) => {
    const query = (textToSend || inputText).trim();
    if (!query || isLoading) return;

    const userMsg: Message = {
      id: `user-${Date.now()}`,
      sender: 'user',
      text: query,
    };

    setMessages((prev) => [...prev, userMsg]);
    setInputText('');
    setIsLoading(true);

    try {
      const response: AgentQueryResponse = await api.askAgent72(institutionId, query, period);
      const agentMsg: Message = {
        id: `agent-${Date.now()}`,
        sender: 'agent',
        text: response.answer,
        confidence: response.confidence,
        groundingSources: response.grounding_sources,
        relatedMetrics: response.related_metrics,
        suggestedQuestions: response.suggested_questions,
        disclaimer: response.leadership_disclaimer,
      };
      setMessages((prev) => [...prev, agentMsg]);
    } catch (err: any) {
      console.error('Ask Agent 72 error:', err);
      const errorMsg: Message = {
        id: `agent-error-${Date.now()}`,
        sender: 'agent',
        text: 'Agent 72 encountered an error while synthesizing institutional evidence. Please verify that the backend server is running.',
      };
      setMessages((prev) => [...prev, errorMsg]);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex flex-col md:flex-row h-[calc(100vh-17rem)] min-h-[580px] bg-white rounded-2xl border border-slate-200 shadow-2xs overflow-hidden">
      {/* Left Side Section: Robot Standing in the Center */}
      <div className="hidden md:flex md:w-72 lg:w-80 shrink-0 bg-gradient-to-b from-blue-50/70 via-slate-50/50 to-white border-r border-slate-200 p-5 flex-col items-center justify-between text-center relative overflow-hidden select-none">
        {/* Ambient Halo & Gradient Background */}
        <div className="absolute -top-12 -left-12 w-48 h-48 bg-blue-400/10 rounded-full blur-2xl pointer-events-none" />
        <div className="absolute -bottom-12 -right-12 w-48 h-48 bg-sky-400/10 rounded-full blur-2xl pointer-events-none" />

        {/* Top: Header Pill & Branding */}
        <div className="relative z-10 space-y-1">
          <div className="inline-flex items-center gap-1.5 px-3 py-1 bg-white border border-blue-200 text-blue-800 text-xs font-semibold rounded-full shadow-2xs">
            <Sparkles className="w-3.5 h-3.5 text-blue-600" />
            <span>AI Strategic Advisor</span>
          </div>
          <h2 className="text-base font-bold text-slate-800 tracking-tight">Agent 72</h2>
          <p className="text-[11px] text-slate-500">Vignan's University Decision Support</p>
        </div>

        {/* Center: Robot Image Standing Proudly */}
        <div className="relative z-10 flex flex-col items-center justify-center my-auto py-2">
          <div className="relative flex items-center justify-center">
            {/* Glowing Backdrop Ring */}
            <div className="absolute w-36 h-36 bg-blue-400/20 rounded-full blur-xl pointer-events-none" />
            <img
              src="/agent72-robot.png"
              alt="Agent 72 Standing Robot Advisor"
              className="w-44 h-44 lg:w-48 lg:h-48 object-contain relative z-10 animate-float drop-shadow-md transition-transform duration-300 hover:scale-105"
            />
          </div>

          <div className="mt-3 inline-flex items-center gap-1.5 px-3 py-1 bg-white border border-slate-200 rounded-full text-[11px] font-semibold text-slate-700 shadow-2xs">
            <span className="w-2 h-2 rounded-full bg-emerald-500 animate-ping" />
            <span className="w-2 h-2 rounded-full bg-emerald-500 -ml-3.5" />
            <span>Standing by for queries</span>
          </div>
        </div>

        {/* Bottom: Institutional Assurance */}
        <div className="relative z-10 w-full pt-3 border-t border-slate-200/80 space-y-1.5 text-[11px] text-slate-500">
          <div className="flex items-center justify-center gap-1 font-semibold text-slate-700">
            <ShieldCheck className="w-3.5 h-3.5 text-blue-600" />
            <span>Zero-Fabrication Intelligence</span>
          </div>
          <p className="text-[10px] text-slate-400 leading-tight">
            Deterministic domain models grounded in verified university metrics
          </p>
        </div>
      </div>

      {/* Right Side Section: Interactive Chat Stream */}
      <div className="flex-1 flex flex-col min-w-0 bg-white">
        {/* Chat Messages Scrollable Body */}
        <div className="flex-1 overflow-y-auto p-4 sm:p-5 space-y-4">
          {messages.map((m) => (
            <div
              key={m.id}
              className={`flex flex-col ${m.sender === 'user' ? 'items-end' : 'items-start'}`}
            >
              <div className="flex items-center gap-1.5 mb-1 text-[11px] text-slate-400 font-medium">
                {m.sender === 'agent' ? (
                  <>
                    <div className="w-5 h-5 rounded-full overflow-hidden border border-blue-200 shrink-0 bg-blue-50 flex items-center justify-center">
                      <img src="/agent72-robot.png" alt="72" className="w-full h-full object-cover" />
                    </div>
                    <span className="font-bold text-slate-700">Agent 72</span>
                    {m.confidence !== undefined && (
                      <span className="text-emerald-700 font-semibold bg-emerald-50 px-1.5 py-0.2 rounded">
                        {Math.round(m.confidence * 100)}% Confidence
                      </span>
                    )}
                  </>
                ) : (
                  <span className="font-semibold text-slate-600">Institutional Leadership</span>
                )}
              </div>

              <div
                className={`max-w-3xl lg:max-w-4xl p-4 sm:p-5 rounded-2xl text-xs sm:text-sm leading-relaxed ${
                  m.sender === 'user'
                    ? 'bg-blue-600 text-white rounded-tr-none whitespace-pre-line'
                    : 'bg-slate-50 text-slate-800 border border-slate-200 rounded-tl-none space-y-3'
                }`}
              >
                {m.sender === 'user' ? (
                  <div>{m.text}</div>
                ) : (
                  <StructuredMessageView content={m.text} />
                )}

                {/* Traceable Grounding Sources */}
                {m.groundingSources && m.groundingSources.length > 0 && (
                  <div className="pt-2.5 border-t border-slate-200/80 text-xs text-slate-500 space-y-1">
                    <div className="flex items-center gap-1 font-semibold text-[11px] text-slate-600">
                      <Database className="w-3 h-3 text-blue-600" />
                      <span>Grounding Sources ({m.groundingSources.length}):</span>
                    </div>
                    <div className="flex flex-wrap gap-1.5 pt-0.5">
                      {m.groundingSources.slice(0, 4).map((src, i) => (
                        <span
                          key={i}
                          className="inline-flex items-center gap-1 bg-white px-2 py-0.5 rounded border border-slate-200 font-mono text-[10px] text-slate-700"
                        >
                          {src.type || 'Evidence'}: {src.metric || src.title || src.id || 'Observation'}
                        </span>
                      ))}
                    </div>
                  </div>
                )}

                {/* Related Metrics */}
                {m.relatedMetrics && m.relatedMetrics.length > 0 && (
                  <div className="pt-1 text-[11px] text-slate-500">
                    <span className="font-semibold text-slate-600">Related Metrics: </span>
                    <span className="font-mono text-blue-700">{m.relatedMetrics.join(', ')}</span>
                  </div>
                )}

                {/* Suggested Follow-up Questions */}
                {m.suggestedQuestions && m.suggestedQuestions.length > 0 && (
                  <div className="pt-2 border-t border-slate-200/80 space-y-1">
                    <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">
                      Suggested Follow-Ups:
                    </span>
                    <div className="flex flex-wrap gap-1.5 pt-1">
                      {m.suggestedQuestions.map((q, idx) => (
                        <button
                          key={idx}
                          onClick={() => handleSend(q)}
                          className="inline-flex items-center gap-1 text-[11px] bg-white hover:bg-blue-50 text-blue-700 px-2 py-1 rounded-lg border border-slate-200 transition"
                        >
                          <ArrowRight className="w-3 h-3 text-blue-500" />
                          <span>{q}</span>
                        </button>
                      ))}
                    </div>
                  </div>
                )}

                {/* Leadership Disclaimer in chat */}
                {m.disclaimer && (
                  <div className="pt-2 border-t border-slate-200 text-[10px] text-slate-400 italic">
                    {m.disclaimer}
                  </div>
                )}
              </div>
            </div>
          ))}

          {isLoading && (
            <div className="flex items-center gap-2 p-3 bg-slate-50 border border-slate-200 rounded-xl text-xs text-slate-500 w-fit">
              <Sparkles className="w-4 h-4 text-blue-600 animate-spin" />
              <span>Agent 72 is synthesizing real institutional evidence...</span>
            </div>
          )}
        </div>

        {/* Suggested Quick Prompt Chips */}
        <div className="p-3 bg-slate-50/80 border-t border-slate-200 overflow-x-auto scrollbar-none flex items-center gap-1.5">
          <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 whitespace-nowrap mr-1">
            Quick Prompts:
          </span>
          {quickPrompts.map((p, idx) => (
            <button
              key={idx}
              onClick={() => handleSend(p)}
              disabled={isLoading}
              className="text-xs bg-white hover:bg-slate-100 text-slate-700 font-medium px-2.5 py-1 rounded-lg border border-slate-200/90 whitespace-nowrap shadow-2xs transition shrink-0"
            >
              {p}
            </button>
          ))}
        </div>

        {/* Message Input Box */}
        <form
          onSubmit={(e) => {
            e.preventDefault();
            handleSend();
          }}
          className="p-3 bg-white border-t border-slate-200 flex items-center gap-2"
        >
          <input
            type="text"
            value={inputText}
            onChange={(e) => setInputText(e.target.value)}
            placeholder="Ask Agent 72 about institutional strategy, department focus, or targets..."
            disabled={isLoading}
            className="flex-1 bg-slate-50 border border-slate-200 rounded-xl px-4 py-2.5 text-xs text-slate-800 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 transition"
          />
          <button
            type="submit"
            disabled={!inputText.trim() || isLoading}
            className="p-2.5 bg-blue-600 hover:bg-blue-700 disabled:bg-slate-200 text-white rounded-xl shadow-xs transition"
          >
            <Send className="w-4 h-4" />
          </button>
        </form>
      </div>
    </div>
  );
};
