import React, { useState } from 'react';
import { Send, Sparkles, Database, ArrowRight, ShieldCheck, Compass, AlertCircle, FileText } from 'lucide-react';
import { api } from '../../api/client';
import { AgentQueryResponse } from '../../api/types';
import { StructuredMessageView } from './StructuredMessageView';
import agent72Robot from '../../assets/agent72-robot.png';

interface Message {
  id: string;
  sender: 'user' | 'agent';
  text: string;
  confidence?: number;
  groundingSources?: any[];
  relatedMetrics?: string[];
  suggestedQuestions?: string[];
  disclaimer?: string;
}

interface AskAgent72ViewProps {
  institutionId: string;
  period: string;
}

export const AskAgent72View: React.FC<AskAgent72ViewProps> = ({ institutionId, period }) => {
  const [messages, setMessages] = useState<Message[]>([
    {
      id: 'welcome-1',
      sender: 'agent',
      text: "Greetings. I am Agent 72, an institutional strategic planning and decision-support agent.\n\nI can synthesize verified evidence across current positions, trajectory forecasts, strategic intelligence, candidate options, and execution reviews for institutional governing bodies. What strategic inquiry would you like to explore?",
      disclaimer:
        'Strategic plans and analyses generated by Agent 72 are decision-support artifacts. Final approval, resource allocation and institutional strategy remain with institutional leadership/governing bodies.',
    },
  ]);
  const [inputText, setInputText] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  const quickPrompts = [
    'What should the Computer Science and Engineering department focus on over the next academic year, given our placement trends, research output, and faculty profile?',
    'Where are we currently underperforming against targets?',
    'What strategic risks should leadership focus on?',
    'Which strategic options are highest priority?',
    'How is our strategic plan progressing?',
    'What targets are currently at risk?',
  ];

  const handleSend = async (textToSend?: string) => {
    const query = (textToSend || inputText).trim();
    if (!query || isLoading) return;

    const userMsg: Message = {
      id: `user-${Date.now()}`,
      sender: 'user',
      text: query,
    };

    setMessages((prev) => [...prev, userMsg]);
    setInputText('');
    setIsLoading(true);

    try {
      const response: AgentQueryResponse = await api.askAgent72(institutionId, query, period);
      const agentMsg: Message = {
        id: `agent-${Date.now()}`,
        sender: 'agent',
        text: response.answer,
        confidence: response.confidence,
        groundingSources: response.grounding_sources,
        relatedMetrics: response.related_metrics,
        suggestedQuestions: response.suggested_questions,
        disclaimer: response.leadership_disclaimer,
      };
      setMessages((prev) => [...prev, agentMsg]);
    } catch (err: any) {
      console.error('Ask Agent 72 error:', err);
      const errorMsg: Message = {
        id: `agent-error-${Date.now()}`,
        sender: 'agent',
        text: 'Agent 72 encountered an error while synthesizing institutional evidence. Please verify that the backend API is active.',
      };
      setMessages((prev) => [...prev, errorMsg]);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex flex-col lg:flex-row h-[calc(100vh-16rem)] min-h-[600px] bg-card rounded-xl border border-app-border shadow-xs overflow-hidden">
      {/* Left Column: Institutional Advisory Profile & Grounding Protocol */}
      <div className="hidden lg:flex lg:w-80 shrink-0 bg-[#F5F9FC] border-r border-app-border p-5 flex-col justify-between select-none">
        <div className="space-y-4">
          <div className="flex items-center gap-2.5">
            <div className="w-10 h-10 rounded-xl overflow-hidden border border-app-border bg-white p-0.5 shadow-xs shrink-0 flex items-center justify-center">
              <img src={agent72Robot} alt="Agent 72" className="w-full h-full object-contain" />
            </div>
            <div>
              <h2 className="text-sm font-bold text-navy tracking-tight">Ask Agent 72</h2>
              <p className="text-[11px] text-muted font-medium">Strategic Decision Support</p>
            </div>
          </div>

          <div className="p-3 bg-white rounded-lg border border-app-border space-y-2">
            <div className="flex items-center gap-1.5 text-xs font-semibold text-navy">
              <ShieldCheck className="w-4 h-4 text-inst-blue" />
              <span>Evidence-Grounded Querying</span>
            </div>
            <p className="text-[11px] text-muted leading-relaxed">
              Inquiries are synthesized strictly against verified institutional metrics, historical trajectories, and formal strategic options. Zero metric fabrication.
            </p>
          </div>

          <div className="space-y-2">
            <div className="text-[10px] font-bold uppercase tracking-wider text-muted px-1">
              Active Context
            </div>
            <div className="p-2.5 bg-white rounded-lg border border-app-border text-xs space-y-1">
              <div className="flex justify-between text-[11px]">
                <span className="text-muted">Target Period:</span>
                <span className="font-semibold text-primary-text">{period || '2024-25'}</span>
              </div>
              <div className="flex justify-between text-[11px]">
                <span className="text-muted">Domain Mode:</span>
                <span className="font-semibold text-inst-blue">Executive Decision Support</span>
              </div>
              <div className="flex justify-between text-[11px]">
                <span className="text-muted">Pipeline:</span>
                <span className="font-mono text-[10px] text-primary-text">Phases 1–8 Integrated</span>
              </div>
            </div>
          </div>

          <div className="space-y-1.5">
            <div className="text-[10px] font-bold uppercase tracking-wider text-muted px-1">
              Recommended Inquiries
            </div>
            <div className="space-y-1">
              {quickPrompts.slice(0, 3).map((prompt, idx) => (
                <button
                  key={idx}
                  onClick={() => handleSend(prompt)}
                  disabled={isLoading}
                  className="w-full text-left p-2 text-[11px] text-primary-text hover:text-inst-blue bg-white hover:bg-sky-accent/50 rounded-md border border-app-border transition leading-snug flex items-start gap-1.5"
                >
                  <ArrowRight className="w-3 h-3 text-inst-blue shrink-0 mt-0.5" />
                  <span className="line-clamp-2">{prompt}</span>
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Bottom Disclaimer */}
        <div className="pt-3 border-t border-app-border">
          <div className="flex items-start gap-1.5 p-2 bg-amber-50/70 border border-amber-200/80 rounded-md text-[10px] text-amber-900 leading-tight">
            <AlertCircle className="w-3.5 h-3.5 text-amber-700 shrink-0 mt-0.5" />
            <span>Advisory only. Final strategic and budget approval remains with governing leadership.</span>
          </div>
        </div>
      </div>

      {/* Right Column: Query & Response Stream */}
      <div className="flex-1 flex flex-col min-w-0 bg-white">
        {/* Messages Body */}
        <div className="flex-1 overflow-y-auto p-4 sm:p-6 space-y-5">
          {messages.map((m) => (
            <div
              key={m.id}
              className={`flex flex-col ${m.sender === 'user' ? 'items-end' : 'items-start'}`}
            >
              <div className="flex items-center gap-1.5 mb-1 text-[11px] text-muted font-medium">
                {m.sender === 'agent' ? (
                  <>
                    <div className="w-10 h-10 rounded-xl overflow-hidden border border-[#D7E4EE] bg-white p-1 flex items-center justify-center shrink-0 shadow-xs">
                      <img src={agent72Robot} alt="Agent 72" className="w-full h-full object-contain" />
                    </div>
                    <span className="font-bold text-navy">Agent 72</span>
                    {m.confidence !== undefined && (
                      <span className="text-success font-semibold bg-[#E8F4FB] text-[10px] px-1.5 py-0.5 rounded border border-[#D7E4EE]">
                        {Math.round(m.confidence * 100)}% Evidence Confidence
                      </span>
                    )}
                  </>
                ) : (
                  <span className="font-semibold text-primary-text">Institutional Leadership</span>
                )}
              </div>

              <div
                className={`max-w-3xl lg:max-w-5xl xl:max-w-6xl w-full p-4 sm:p-5 rounded-xl text-xs sm:text-sm leading-relaxed ${
                  m.sender === 'user'
                    ? 'bg-navy text-white rounded-tr-none whitespace-pre-line shadow-2xs'
                    : 'bg-[#F5F9FC] text-primary-text border border-app-border rounded-tl-none space-y-3 shadow-2xs'
                }`}
              >
                {m.sender === 'user' ? (
                  <div>{m.text}</div>
                ) : (
                  <StructuredMessageView content={m.text} />
                )}

                {/* Traceable Grounding Sources */}
                {m.groundingSources && m.groundingSources.length > 0 && (
                  <div className="pt-3 border-t border-app-border text-xs text-muted space-y-1.5">
                    <div className="flex items-center gap-1.5 font-semibold text-[11px] text-navy">
                      <Database className="w-3.5 h-3.5 text-inst-blue" />
                      <span>Grounded Against ({m.groundingSources.length} Institutional Sources):</span>
                    </div>
                    <div className="flex flex-wrap gap-1.5 pt-0.5">
                      {m.groundingSources.slice(0, 6).map((src, i) => (
                        <span
                          key={i}
                          className="inline-flex items-center gap-1 bg-white px-2 py-0.5 rounded border border-app-border font-mono text-[10px] text-primary-text"
                        >
                          <FileText className="w-2.5 h-2.5 text-inst-blue" />
                          <span>{src.type || 'Evidence'}: {src.metric || src.title || src.id || 'Observation'}</span>
                        </span>
                      ))}
                    </div>
                  </div>
                )}

                {/* Related Metrics */}
                {m.relatedMetrics && m.relatedMetrics.length > 0 && (
                  <div className="pt-1.5 text-[11px] text-muted flex items-center gap-1.5 flex-wrap">
                    <span className="font-semibold text-navy">Related Metrics:</span>
                    {m.relatedMetrics.map((rm, idx) => (
                      <span key={idx} className="font-mono text-[10px] bg-white px-1.5 py-0.5 rounded border border-app-border text-inst-blue">
                        {rm}
                      </span>
                    ))}
                  </div>
                )}

                {/* Suggested Follow-up Questions */}
                {m.suggestedQuestions && m.suggestedQuestions.length > 0 && (
                  <div className="pt-2.5 border-t border-app-border space-y-1.5">
                    <span className="text-[10px] font-bold uppercase tracking-wider text-muted">
                      Suggested Follow-Ups:
                    </span>
                    <div className="flex flex-wrap gap-1.5 pt-0.5">
                      {m.suggestedQuestions.map((q, idx) => (
                        <button
                          key={idx}
                          onClick={() => handleSend(q)}
                          className="inline-flex items-center gap-1 text-[11px] bg-white hover:bg-sky-accent text-inst-blue font-medium px-2.5 py-1 rounded-md border border-app-border transition shadow-2xs"
                        >
                          <ArrowRight className="w-3 h-3 text-inst-blue" />
                          <span>{q}</span>
                        </button>
                      ))}
                    </div>
                  </div>
                )}

                {/* Leadership Disclaimer in response */}
                {m.disclaimer && (
                  <div className="pt-2 border-t border-app-border text-[10px] text-muted italic">
                    {m.disclaimer}
                  </div>
                )}
              </div>
            </div>
          ))}

          {isLoading && (
            <div className="flex items-center gap-2 p-3 bg-sky-accent/50 border border-app-border rounded-lg text-xs text-navy w-fit shadow-2xs">
              <Sparkles className="w-4 h-4 text-inst-blue animate-spin" />
              <span className="font-medium">Agent 72 is synthesizing institutional evidence from database...</span>
            </div>
          )}
        </div>

        {/* Quick Prompts Bar */}
        <div className="p-3 bg-[#F5F9FC] border-t border-app-border overflow-x-auto flex items-center gap-1.5">
          <span className="text-[10px] font-bold uppercase tracking-wider text-muted whitespace-nowrap mr-1">
            Quick Prompts:
          </span>
          {quickPrompts.map((p, idx) => (
            <button
              key={idx}
              onClick={() => handleSend(p)}
              disabled={isLoading}
              className="text-xs bg-white hover:bg-sky-accent text-primary-text hover:text-navy font-medium px-3 py-1 rounded-md border border-app-border whitespace-nowrap shadow-2xs transition shrink-0"
            >
              {p}
            </button>
          ))}
        </div>

        {/* Input Bar */}
        <form
          onSubmit={(e) => {
            e.preventDefault();
            handleSend();
          }}
          className="p-3 bg-white border-t border-app-border flex items-center gap-2"
        >
          <input
            type="text"
            value={inputText}
            onChange={(e) => setInputText(e.target.value)}
            placeholder="Ask Agent 72 about departmental focus, trajectory risks, option tradeoffs, or target gaps..."
            disabled={isLoading}
            className="flex-1 bg-[#F5F9FC] border border-app-border rounded-lg px-4 py-2.5 text-xs text-primary-text placeholder:text-muted focus:outline-none focus:ring-1 focus:ring-inst-blue focus:border-inst-blue transition"
          />
          <button
            type="submit"
            disabled={!inputText.trim() || isLoading}
            className="px-4 py-2.5 bg-navy hover:bg-navy/90 disabled:bg-slate-200 disabled:text-slate-400 text-white text-xs font-semibold rounded-lg shadow-xs transition flex items-center gap-1.5"
          >
            <span>Query</span>
            <Send className="w-3.5 h-3.5" />
          </button>
        </form>
      </div>
    </div>
  );
};
