"""DTOs for grounded Agent 72 Strategic Query API."""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class AgentQueryRequestDTO(BaseModel):
    """Request DTO for asking Agent 72 strategic questions."""

    institution_id: str = Field(..., description="Target Institution ID or Code")
    query: str = Field(..., min_length=3, description="Strategic question for Agent 72")
    analysis_period: Optional[str] = Field(None, description="Optional target academic analysis period")


class AgentQueryResponseDTO(BaseModel):
    """Response DTO for grounded Agent 72 strategic query answers."""

    answer: str = Field(..., description="Grounded, evidence-backed narrative answer")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score based on underlying evidence")
    grounding_sources: List[Dict[str, Any]] = Field(
        default_factory=list, description="Traceable sources and evidence items backing the answer"
    )
    related_metrics: List[str] = Field(
        default_factory=list, description="Canonical metric keys relevant to the inquiry"
    )
    suggested_questions: List[str] = Field(
        default_factory=list, description="Contextual follow-up strategic questions"
    )
    leadership_disclaimer: str = Field(
        default=(
            "Strategic plans and analyses generated by Agent 72 are decision-support artifacts. "
            "Final approval, resource allocation and institutional strategy remain with institutional leadership/governing bodies."
        ),
        description="Mandatory leadership decision-support disclaimer",
    )
